baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = "../.."

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

customCSS = ["", ""]

#This theme can generate a multi-level theme.
#Use the weight= to specify the order of menu items, and the parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

# Paramaters for the whole site
[params]
  title = "Alpha Church"
  subtitle = "Another Church Theme"
  author = "Daniel Saunders"

  #Paramaters for the home/landing page
  [params.landing.banner]
    image = "/img/banner.jpg"

    [[params.landing.banner.button]]
      url = "/contact"
      text = "Get in touch"
      type = "special"

    [[params.landing.banner.button]]
      url = "/about"
      text = "Find out more"

  [params.landing.feature]
    title = "A great church near you."
    text = "Grow in love. Go in love."
    image = ""
