baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = "../.."

[menu]

[params]
  title = "Alpha Church"
  subtitle = "Another Church Theme"

  [params.landing.banner]
    image = "/img/banner.jpg"
